### ISSUE TITLE
Can´t run battery patcher, gets stuck on error

### ISSUE THREAD

**Issue by kasti0** [1Revenger1/BatteryPatcher#3]
when I run battery patcher it always gets stuck on an error which I don´t know how to fix
newest NodeJS version is installed, iasl is in the executables folder and my DSDT in the results folder

```
TypeError: Cannot read property 'scope' of undefined
    at /Users/USERNAME/Documents/Hackintosh/tools/BatteryPatcher-master/program/SSDT.js:211:45
    at Array.forEach (<anonymous>)
    at /Users/USERNAME/Documents/Hackintosh/tools/BatteryPatcher-master/program/SSDT.js:183:25
    at Array.forEach (<anonymous>)
    at /Users/USERNAME/Documents/Hackintosh/tools/BatteryPatcher-master/program/SSDT.js:162:26
    at Array.forEach (<anonymous>)
    at new SSDT (/Users/USERNAME/Documents/Hackintosh/tools/BatteryPatcher-master/program/SSDT.js:144:18)
    at BatteryPatcher.crawler (/Users/USERNAME/Documents/Hackintosh/tools/BatteryPatcher-master/program/Index.js:295:22)
    at BatteryPatcher.main (/Users/USERNAME/Documents/Hackintosh/tools/BatteryPatcher-master/program/Index.js:417:28)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
npm ERR! code 1
npm ERR! path /Users/USERNAME/Documents/Hackintosh/tools/BatteryPatcher-master
npm ERR! command failed
npm ERR! command sh -c npm run build --silent && npm run run --silent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/USERNAME/.npm/_logs/2021-01-09T21_24_16_856Z-debug.log
```

**Comment by kasti0** [comment]
that´s the DSDT I´m trying to patch. no luck so far, I always get the same error

[DSDT.aml.zip](https://github.com/1Revenger1/BatteryPatcher/files/5808968/DSDT.aml.zip)
