### ISSUE TITLE
Unknown ECAV

### ISSUE THREAD

**Issue by gsjv2** [1Revenger1/BatteryPatcher#4]
Running npm run start produces the following error:

`Unknown ECAV
(node:18100) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'scope' of undefined
    at C:\Users\username\Desktop\BatteryPatcher-master\program\SSDT.js:212:45
    at Array.forEach (<anonymous>)
    at C:\Users\username\Desktop\BatteryPatcher-master\program\SSDT.js:184:25
    at Array.forEach (<anonymous>)
    at C:\Users\username\Desktop\BatteryPatcher-master\program\SSDT.js:163:26
    at Array.forEach (<anonymous>)
    at new SSDT (C:\Users\username\Desktop\BatteryPatcher-master\program\SSDT.js:145:18)
    at BatteryPatcher.crawler (C:\Users\username\Desktop\BatteryPatcher-master\program\Index.js:307:22)
    at BatteryPatcher.main (C:\Users\username\Desktop\BatteryPatcher-master\program\Index.js:429:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Attached is the DSDT.aml extracted with acpidump.exe
[DSDT.zip](https://github.com/1Revenger1/BatteryPatcher/files/6313041/DSDT.zip)

Does ECAV need to be added as a scope?

**Comment by gsjv2** [comment]
Here is the error using the latest npm:

`Unknown ECAV
C:\Users\grant\Desktop\BatteryPatcher-master\program\SSDT.js:212
                            if (unmodMethod.scope == undefined || unmodMethod.scope == "\\")
                                            ^

TypeError: Cannot read property 'scope' of undefined
    at C:\Users\username\Desktop\BatteryPatcher-master\program\SSDT.js:212:45
    at Array.forEach (<anonymous>)
    at C:\Users\username\Desktop\BatteryPatcher-master\program\SSDT.js:184:25
    at Array.forEach (<anonymous>)
    at C:\Users\username\Desktop\BatteryPatcher-master\program\SSDT.js:163:26
    at Array.forEach (<anonymous>)
    at new SSDT (C:\Users\username\Desktop\BatteryPatcher-master\program\SSDT.js:145:18)
    at BatteryPatcher.crawler (C:\Users\username\Desktop\BatteryPatcher-master\program\Index.js:307:22)
    at BatteryPatcher.main (C:\Users\username\Desktop\BatteryPatcher-master\program\Index.js:429:28)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)`
